export class p{
    constructor(
        public id? : number,
        public nome? : string,
        public thumb? : string,
        public img? : string,
        public desc1? : string,
        public desc2? : string,
        public desc3? : string,
        public Tipo1?: string,
        public Tipo2?: string,
        public Habilidade1?: string,
        public Habilidade2?: string,
        public especie? : string,
        public Catchrate? : string,
        public EggGroup1? : string,
        public EggGroup2? : string,
        public Tempo_nasc? : string,
        public Altura?: string,
        public Peso?: string,
        public hp? : string,
        public ataque? : string,
        public defesa? : string,
        public sp_ata? : string,
        public sp_defesa? : string,
        public speed? : string,
        public levelup? : string,
        public imgpokeprin? : string,
        public pokeinicial? : string,
        public evolucao1? : string,
        public imgevo1? : string,
        public evolucao2? : string,
        public imgevo2? : string) { }
    }